### ISSUE TITLE
Pick a tranquil image based on semantics of the entry

### ISSUE THREAD

**Issue by landlessness** [MelissaRose/tranquil#1]
Once a user enters an entry let's go find an image that is appropriate to their mood yet soothing.

something like:
`GET http://api.flickr.com/services/rest/?&method=flickr.people.getPublicPhotos`

**Comment by MelissaRose** [comment]
Great issue, but not what I had envisioned.  User knows they're feeling anxious, so no need to describe it.  All they need to do hit a button, depending on whether they want to look at images or play music.

**Comment by landlessness** [comment]
Ah. Gotchya. Cool.
